# Generated by Django 5.0.6 on 2024-05-18 16:16

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_type', models.CharField(default='euro', max_length=9, unique=True)),
            ],
            options={
                'verbose_name': 'tipo de divisa',
                'verbose_name_plural': 'tipos de divisa',
            },
        ),
        migrations.CreateModel(
            name='Kind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(default='video', unique=True, verbose_name='tipo')),
            ],
            options={
                'verbose_name': 'tipo',
                'verbose_name_plural': 'tipos',
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(default='Alcaucín', unique=True, verbose_name='ciudad')),
            ],
            options={
                'verbose_name': 'Sede',
                'verbose_name_plural': 'Sedes',
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='assets', verbose_name='Video')),
                ('title', models.IntegerField(verbose_name='title')),
                ('client', models.ForeignKey(db_column='username', default='naruto', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='cliente')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(unique=True, verbose_name='producto')),
                ('image', models.ImageField(default='camera.png', upload_to='products', verbose_name='imagen')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='precio/ud')),
                ('stock', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='stock')),
                ('description', models.TextField(verbose_name='descripción')),
                ('currency_type', models.ForeignKey(db_column='currency_type', default='euro', on_delete=django.db.models.deletion.CASCADE, to='api.currencytype', to_field='currency_type')),
                ('kind', models.ForeignKey(db_column='kind', on_delete=django.db.models.deletion.CASCADE, to='api.kind', to_field='kind')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='unidades')),
                ('discount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='descuento')),
                ('price_final', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='precio final')),
                ('date_sale', models.DateField(default=django.utils.timezone.now, editable=False, verbose_name='Fecha venta')),
                ('client', models.ForeignKey(db_column='username', default='pyCampaDB', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='cliente')),
                ('product', models.ForeignKey(db_column='product', default='camara', on_delete=django.db.models.deletion.CASCADE, to='api.product', to_field='product', verbose_name='producto')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=8, unique=True, verbose_name='Título')),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(default='key.png', upload_to='services', verbose_name='Imagen')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('currency_types', models.ForeignKey(db_column='currency_types', on_delete=django.db.models.deletion.CASCADE, to='api.currencytype', to_field='currency_type')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'managed': 'Servicio',
            },
        ),
    ]
